version: "3.8"

services:
    postgres-db:
        image: postgres:13.3
        container_name: db-postgres-for-2-task
        environment:
            POSTGRES_DB: "postgresdb"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "123456789"
        volumes:
            - ./my-postgres-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"