version: "3.8"

services:
    postgres-db:
        image: postgres:13.3
        container_name: db-postgres-for-2-task
        environment:
            POSTGRES_DB: "postgresdb"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "123456789"
        volumes:
            - ./my-postgres-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    main-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: audio-service
        restart: always
        depends_on:
            - postgres-db
        ports:
            - "8000:8000"
        command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
        environment:
            DB_HOST: "db-postgres-for-2-task"
            DB_PORT: "5432"
            DB_USER: "user"
            DB_PASSWORD: "123456789"
            DB_NAME: "postgresdb"
            DB_TYPE: "postgresql+asyncpg"
